<?php /* @var $this Authorizedby_Trustseal_Block_Authorizedby */ ?>
<?php if ($this->isEnabled()): ?>
    <?php $currentProduct = Mage::registry('current_product'); ?>
    <?php $currentProductId = false; ?>
    <?php if ($currentProduct && $currentProduct->getId()): ?>
        <?php $attributeCode = $this->getProductVerificationAttribute(); ?>
        <?php $currentProductId = $currentProduct->getData($attributeCode); ?>
    <?php endif; ?>
    <script src="https://app.authorized.by/trustedretailers/api.js"></script>
    <?php $position = $this->getBadgePosition(); ?>
    <?php $language = $this->getLanguage(); ?>
    <script>
        var options = {
            language: "<?php echo $language; ?>",
            "embeddedOriginal.container.zIndex": <?php echo $this->getZIndex(); ?>
        };

        <?php if ($this->isStandardBadgeEnabled()): ?>
            options.position = "<?php echo $position; ?>";
            <?php if ('right-fixed' === $position): ?>
                options.<?php echo $this->getBadgePositionAlignment(); ?> = "<?php echo $this->getBadgePositionMargin() . $this->getBadgePositionUnit(); ?>";
            <?php endif; ?>
        <?php endif; ?>

        <?php if ($this->isMobileEnabled()): ?>
            options.enableMobile = "true";
        <?php endif; ?>

        <?php if ($currentProductId): ?>
            options.productId = "<?php echo $currentProductId; ?>"
        <?php endif; ?>

        document.addEventListener("DOMContentLoaded", function () {
            new AuthorizedByBadge(options).init();
        });
    </script>
<?php endif; ?>
